{% set version = "1.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plot3d
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plot3D_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plot3D/plot3D_{{ version }}.tar.gz
  sha256: d04a45197646fb36bc38870c1c2351cb56b912bd772b1ebfa25eaeef35fda9c0

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-misc3d
  run:
    - r-base
    - r-misc3d

test:
  commands:
    - $R -e "library('plot3D')"           # [not win]
    - "\"%R%\" -e \"library('plot3D')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=plot3D
  license: GPL-3.0-or-later
  summary: Functions for viewing 2-D and 3-D data, including perspective plots, slice plots, surface plots, scatter plots, etc. Includes data sets from oceanography.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
