{% set version = "1.4.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-plot3d
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plot3D_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plot3D/plot3D_{{ version }}.tar.gz
  sha256: 88b17af8b0eeb16e0ab69378c800eb843f5834acc100eb79e54338b9f1a5fd75

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-misc3d
  run:
    - r-base
    - r-misc3d

test:
  commands:
    - $R -e "library('plot3D')"           # [not win]
    - "\"%R%\" -e \"library('plot3D')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=plot3D
  license: GPL-3.0-or-later
  summary: Functions for viewing 2-D and 3-D data, including perspective plots, slice plots, surface plots, scatter plots, etc. Includes data sets from oceanography.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
