{% set version = "1.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plot3d
  version: {{ version|replace("-", "_") }}

source:
  fn: plot3D_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/plot3D_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/plot3D/plot3D_{{ version }}.tar.gz

  sha256: b9e4ec2789e34ad249318900e186868650e1a33466b385cb492a45466db3dfc9

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-misc3d

  run:
    - r-base
    - r-misc3d

test:
  commands:
    - $R -e "library('plot3D')"  # [not win]
    - "\"%R%\" -e \"library('plot3D')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=plot3D
  license: GPL (>= 3.0)
  summary: Functions for viewing 2-D and 3-D data, including perspective plots, slice plots,
    surface plots, scatter plots, etc. Includes data sets from oceanography.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
