appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: iCBgiRItkWcgqme6zLenZBicfaXJZzryjn5DRzCfMk5a4mi3Gi+3Xye3KEpJNabN32OszbyJQXyOVy47ctRsrzA8aYd/BKzsc7IxHFkYP5k9GCKdy+Hj523B2ExYcJADgKQjfhGZFinz3/As9z/gMoS0JznfNqXBiKaGqs9w6+2DZGen3c8IZZnHpseMczcq+7hz0/nBThqtxMMNhK76WpaVFfMzaHCZqxW9F3cqdODDuGE4lfQ5HPnGquD7bu0kNTweccLY/XLL/ah+Crm+uaipfmWARiIOrzelGRnsx43I02a3BKyhU+85Qlqr4CPCXv0edlq8Tsok4gXm7oH9Etj3YAe+K/rOMGVp5yEai5KqSEaJnZVXg0X3D4kUOmOJgxyxYbAuoiOSdaScJS1a0swsMdewNmeV/Zf4Z/EevBZ4C4Hrf1F5pveKqqEH5kGigG5kvmAiK9C7kCybxA4txIhafwZKiF62W3g0CTuE2EtMKezGkhlYdFAkxRzBn0iCy3cCqhzA1YZ0//9AEUjdiqtRKEdg83iX1ekGUrMLQ49Hwnas8mO17NWZCdfvqL945BPxklfzHhlfe2SEtGeoDVgaMs3g+DRFBinmL2L6o8cZqjgFQ7CHp34Lf2xqI0A0QUanRvDr2x8mLhX8Nnd+CHQXGpWO+0+rGEEutdQTD+I=
