travis:
  secure:
    BINSTAR_TOKEN: JippONDymh9HxHTjE/1P/wiw7f7v8Yz+Gh8sd+sagUFygGb9DsFONe/I/AHa4fh6VZp4MfEQbf5MrfyHoz6ucr6aStYaK7vnJP5Eh1LAoA+wDLiP7zl5V+wsyqhY9KJ7ajilLbzoy1Pzz2Q1IZOxhYj0ZmgtosMlhBrUkQ2U5rjT9tvW1gRSrdA4IMAcdv6snTFjoavwl8WK5mvGGLFhbOJQLfudhHcRNvtxKZfQOo09zj25Lo7Nltl6dhJwUoNm9sw9bRhcWKT6lQktZ4aNJAhgDVrne2ZCKLAvcgdHAGfemxHuBmSeYxbHeJZNnq/Kux1i8eBnQm2N/sw2lg7z7G+xY+xguIX2L4+NTdQYidA3TvdMrnLjHmS+e39m6iixvXk8NswhBVaoB3XOCnbl4zEil5bm3eAn13pJXtiCEXL3828Yl/TJgnXWr1F1mn9FSY9cguKlSh4dLG8MN8o5QvwLHhq8pWthuWj1PiHxliLEc7CL4Fh+Dr4fG4PX9NS5S9gZDPMeFUYBHcZ7y2faV6FJ41kSgrg7qhG7twp2zBE7q3eVf132yNIV0zdl9I4n8AIHahyjp+TYSMoJm0WmMM3a2rciBGNwKZYy9NfBZ5RViPdhVq0LHeGk3dvVnMYuznANPmBa80sv5lNc/GYMqXJNYj3dqbQqjZNCjwANyxs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
