travis:
  secure:
    BINSTAR_TOKEN: NIKTRnsaflPy2XacfJZwo0FL5hNGYGabxrvQpttDMH+EUPjOeChLn2q1fzfJdLINypJFC7wqus+E3paflcXOwVEAYQiYX8c3gvoGvCcxY6Zn4boCb/neMrBMuK5iQkyJWcIT1xzgJ7NgiFGCFYrYcA9yRcklz/QX7t4y9qyUZrZbyFFun/cGyDr8EYD5cF/NfVGLmEpAr/qpJtrp02ftRO1X6jDBdGO1L12/ttXHAZ8VxWQil6iHT5pv/d82zAnWLPHDg51yAd0Y1zMo25kwLcNRGN2YnXctjb1AwwCYZqMi7vSXW0sjcKIMBwS4G56sJIC3bfIF+Bi4GolAXJMk3cFn7WWFZijkpCA2Ter0uB2ThrkVhXEems3kNVGPSKpbODVDxo1QtDus+0T8D+82fR9fVs6/miEz1Y6O7DHOd7frraqX4dMFFsa8tR+uS3deGZa6gcIclX3Pa50aLpcYVlTgTicUTDyrxv6IR7Byg4xlxJj608dCxL/sET78jyHJeiC7NlTeZzI/imxZuUnh54pAZlhMErX7EAPKgWpjAs1iCg2qpWRf2E2j+dxSxbmy2DiBviMcoAufFMH0qTBtl3qE6NBNb9DStqqhbUZFAY1CPoK6yeY3BRcPUXKIupoB3O6QLSIrUq51beZfyS3k9Z8exIntCSd4y7J3zlCfPqs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
